version: 2
updates:
  # Maintain JavaScript dependencies (pnpm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    
    # Grouping related updates into a single PR to save time
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "next*"
          - "eslint*"
          - "typescript"

  # Maintain GitHub Actions (CI/CD)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
